# vim: ft=tmux
set -g mode-style "fg=#eee8d5,bg=#131314"
#
set -g message-style "fg=#eee8d5,bg=#131314"
set -g message-command-style "fg=#eee8d5,bg=#131314"

set -g pane-border-style "fg=#131314"
set -g pane-active-border-style "fg=#eee8d5"

set -g status "on"
set -g status-interval 1
set -g status-justify "left"

set -g status-style "fg=#586e75,bg=#131314"

set -g status-bg "#131314"

set -g status-left-length "100"

set -g status-left-style NONE

setw -g window-status-activity-style "underscore,fg=#839496,bg=#131314"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#839496,bg=#131314"
setw -g window-status-current-format '#[fg=#131314,bg=#eee8d5]#[fg=#b58900,bg=#eee8d5] #I #[fg=#eee8d5,bg=#b58900] #{b:pane_current_path} #[fg=#b58900,bg=#131314,nobold]'
